apiVersion: v1
kind: PersistentVolume
metadata:
  name: small-pv
spec:
  storageClassName: minikube-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"