apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
            name: "mongo"
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - name: mongo-initdb
          mountPath: /docker-entrypoint-initdb.d
        - mountPath: "/data/db"
          name: data-storage
      volumes:
      - name: mongo-initdb
        configMap:
          name: mongo-initdb
      - name: data-storage
        persistentVolumeClaim:
          claimName: nodered-claim