apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-claim
spec:
  storageClassName: minikube-storage
  accessModes:
    - ReadWriteOnce
  volumeName: small-pv
  resources:
    requests:
      storage: 1Gi