apiVersion: v1
kind: Service
metadata:
  name: appdotnet
spec:
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      port: 7006
      targetPort: 7006
      nodePort: 30000
    - name: "https"
      protocol: TCP
      port: 7007
      targetPort: 7007
      nodePort: 30001
  selector:
    app: appdotnet